spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/labor
    username: sa
    password:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
  mapper-locations: classpath*:mappers/**/*.xml
  type-aliases-package: kbiz.labor
prunus:
  websquare:
    adaptor:
      websquare-home: /Users/yongsang/Development/workspace/java/kbiz-labor/runtime/websquare_home
  security:
    authentication:
      tenant: labor
      username-parameter: username
      password-parameter: password
      maximum-password-age: 90 # 비밀번호 유효기간
      maximum-failed-attempts: 5
      lock-time-duration: 3600000 # 1시간
    access:
      whitelisted-endpoints:
        - /**
        - /error
        - /I18N
        - /prunus-biz/**
      ignored-static-endpoints:
        - /**/*.html
        - /websquare/**
        - /resources/**
        - /webjars/**
    authorization:
      enabled: true
      method-authority.enabled: true
      method-authority.activated: false
      base-packages: prunus.biz,kbiz.labor
logging:
  level:
    kbiz.labor: debug
    org.springframework.web: debug
    org.springframework.security: debug

---
spring:
  config:
    activate:
      on-profile: dev, prod
prunus:
  websquare:
    adaptor:
      websquare-home:
